language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - git submodule update --init

script:
  - cd $TRAVIS_BUILD_DIR/
  - cmake --version
  - mkdir -p build/travis
  - make -f makeTravis.mk 
  - ./bin/helloTravis 
  - make clean -f makeTravis.mk

