language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - git submodule update --init

script:
  - cd $TRAVIS_BUILD_DIR/
  - cmake --version
  - mkdir -p build/test
  - cmake test/lib/googletest
  - sudo env "PATH=$PATH" cmake --build test/lib/googletest --target install
  - ls
  - cd test
  - sudo make -f makeTest.mk
  - ./../bin/string-compare
  - make clean -f makeTest.mk

